# This mounts the nfs volume claim into /mnt and continuously
# overwrites /mnt/index.html with the time and hostname of the pod.

apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-busybox-2
spec:
  replicas: 2
  selector:
    name: nfs-busybox-2
  template:
    metadata:
      labels:
        name: nfs-busybox-2
    spec:
      containers:
      - image: busybox
        command:
          - sh
          - -c
          - 'while true; do date > /mnt/index.html; hostname >> /mnt/index.html; sleep $(($RANDOM % 5 + 5)); done'
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
          # name must match the volume name below
          - name: nfs-demo
            mountPath: "/mnt"
            subPath: 'mnt2'
      volumes:
      - name: nfs-demo
        persistentVolumeClaim:
          claimName: nfs-demo-claim
